dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = "dashboard"
urlpatterns = [
    url(r'^$', views.index, name="index"),
]

tindle/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
import tindle.settings as settings

urlpatterns = [
    url(r'^user/', include('user.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^admin/', admin.site.urls, name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

app_name = "user"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^login/$', views.login_page, name="login"),
    url(r'^register/$', views.register, name="register"),
    url(r'^create/$', views.create, name="create"),
    url(r'^auth/$', views.auth, name="auth"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^search/$', views.search, name="search"),
    url(r'^rate/$', views.rate, name="rate"),
]

dashboard/models.py
from django.db import models

# Create your models here.

user/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.db import models




class UserInfo(models.Model):
    picture     = models.ImageField()
    user        = models.OneToOneField(User)
    description = models.TextField(default="")
    birthdate   = models.DateField()
    interest    = models.CharField(max_length=6)
    gender      = models.CharField(max_length=6)


    def __str__(self):
        return str(f"{self.user}")


class Book(models.Model):

    published = models.CharField(max_length=10)
    author    = models.CharField(max_length=1000)
    title     = models.CharField(max_length=1000)
    isbn      = models.CharField(max_length=1000)
    imageurl  = models.CharField(max_length=1000)

    def __str__(self):
        return f"{self.title}"


class Preference(models.Model):
    modified = models.DateTimeField(auto_now=True)
    created  = models.DateTimeField(auto_now_add=True)
    book     = models.OneToOneField(Book, on_delete=models.PROTECT)
    user     = models.ForeignKey(User, on_delete=models.PROTECT)
    rating   = models.PositiveIntegerField(validators=[
        MinValueValidator(1), 
        MaxValueValidator(10)
    ])

    def __str__(self):
        return f"({self.user.username}, {self.book}, {self.rating})"

dashboard/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    return HttpResponse('hi')

user/views.py
import datetime
from bisect import bisect

from .models import UserInfo, Book, Preference

import django.contrib as contrib
from django.core.files import File
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.files.images import ImageFile


from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

def index(request):
    return HttpResponseRedirect('/user/profile')

@login_required
def profile(request):
    return render(request, 'user/profile.html', {
        'user': request.user,
        'rated' : request.user.preference_set.all()
    })



def auth(request):

    post = request.POST
    user = authenticate(request, username=post['username'], password=post['password'])
    referer = request.META.get('HTTP_REFERER')
    if user is None:
        return HttpResponseRedirect(referer)
    contrib.auth.login(request, user)

    link = request.POST.get('next', '/user/profile')
    return HttpResponseRedirect(link)



def login_page(request):
    user = request.user
    if user.is_authenticated():
        return HttpResponseRedirect('/user/profile')
    else:
        return render(request, 'user/login.html', {'next' : request.GET.get('next', '')})

def register(request):
    user = request.user
    if user.is_authenticated():
        return HttpResponseRedirect('/user/profile')
    return render(request, 'user/register.html')



def _create(info_dict): 

    signs = [(1,20,"capricorn"), (2,18,"aquarius"), (3,20,"pisces"), (4,20,"aries"),
             (5,21,"taurus"), (6,21,"gemini"), (7,22,"cancer"), (8,23,"leo"),
             (9,23,"virgo"), (10,23,"libra"), (11,22,"scorpio"), (12,22,"sagittarius"),
             (12,31,"capricorn")]

    def zodiac_image(birthdate):
        date = datetime.datetime.strptime(birthdate, r'%Y-%m-%d')
        zodiac = signs[bisect(signs,(date.month, date.day))][2]
        return f'media/default/{zodiac}.png'


    user = User.objects.create_user(
            username   = info_dict['username'].lower(),
            password   = info_dict['password'],
            email      = info_dict['email'],
            first_name = info_dict['name_first'],
            last_name  = info_dict['name_last'])

    path = zodiac_image(info_dict['birthdate'])
    info = UserInfo.objects.create(
            user      = user,
            picture   = File(open(path, 'rb')),
            gender    = info_dict['gender'],
            interest  = info_dict['interest'],
            birthdate = info_dict['birthdate'])

    user.save()
    info.save()


def create(request):
    post = request.POST
    assert(post['password'] == post['confirm'])

    _create(post)

    return HttpResponseRedirect('/user/login')


def logout(request):
    contrib.auth.logout(request)
    return HttpResponseRedirect('/user/login')


def get_queue(user):
    pass

@login_required
def search(request):

    def annotate(user, queryset):
        rates = {preference.book: preference.rating 
                for preference in user.preference_set.all()}
        books = [book for book in queryset]
        for book in books:
            if book in rates:
                book.rating = int(rates[book])
            else:
                book.rating = 0
        return books



    text = request.GET['query']
    user = request.user
    return render(request, 'user/search.html', {
        'user'   : request.user,
        'isbn'   : annotate(user, Book.objects.filter(isbn__search   = text)),
        'author' : annotate(user, Book.objects.filter(author__search = text)),
        'title'  : annotate(user, Book.objects.filter(title__search  = text))
    })



def rate(request):
    book = Book.objects.get(id = request.POST['bookid'])
    preference = request.user.preference_set.filter(book = book)
    if len(preference):
        if preference[0].rating == 1 + int(request.POST['rating']):
            preference.delete()
        else:
            preference[0].rating = 1 + int(request.POST['rating'])
            preference[0].save()
    else:
        Preference.objects.create(
            user = request.user,
            rating = 1 + int(request.POST['rating']),
            book   = book)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

user/templates/user/login.html
<!DOCTYPE html5>
<html>

<head>
    {% load static %}
    <title>Tindle - Log In</title>
    <script src="https://use.fontawesome.com/68a025e94e.js"></script>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/png">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>


<body>


    <section class="wrap"><section class="wrapin"><section class="main"><div class="head">
        <div class="title"><h0>Tindle</h0><img class="side-logo" src="{% static 'img/favicon.png' %}"></div><br>
        <div class="userinput">
            <form action="{% url 'user:auth' %}" method="post">
                {% csrf_token %}
                {% if next %}
                    <input type="hidden" name="next" value="{{ next }}">
                {% endif %}
                <table class="login"> 
                    <tr>
                        <th class="login" align="right"><p5>USERNAME</p5></th>
                        <th class="login" align="left"><input class="login" type="text" name="username"><br></th>
                    </tr><tr>
                        <th class="login" align="right"><p5>PASSWORD</p5></th>
                        <th class="login" align="left"><input class="login" type="password" name="password"><br></th>
                    </tr><tr>
                        <th class="login" colspan="2" align="center">
                        <input class="login" type="submit" value="LOG IN">
                        <a href="{% url 'user:register'%}">
                            <input class="login" type="button" value="REGISTER">
                        </a>
                        </th>
                    </tr>
                </table>
            </form>
        </div>
    </div></section></section></section>

</body>

</html>

user/templates/user/profile.html
<!DOCTYPE html5>
<html>

<head>
    {% load static %}
    <title>{{ user.username }}</title>
    <script src="https://use.fontawesome.com/68a025e94e.js"></script>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/png">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>


<body>

    <section class="navbar"><section class="navbar-inner">
        <div class="nav-item left">
            <b3>Tindle</b3><img class="nav-logo" src="{% static 'img/favicon.png' %}">
        </div><a href="{% url 'user:logout' %}"><div class="nav-item right gray">
            <p><i class="fa fa-power-off fa-lg down transparent" aria-hidden="true"></i></p>
        </div></a><div class="nav-item right gray">
            <p><i class="fa fa-tachometer fa-lg down transparent" aria-hidden="true"></i></p>
        </div><a href="{% url 'user:profile' %}"><div class="nav-item right gray">
            <p><p6>{{ user.first_name|upper }} {{ user.last_name|upper }}</p6></p>
        </div></a><div class="nav-item right">
            <img class="nav-thumb" src="{{ user.userinfo.picture.url }}">
        </div>


        
        <div class="search">
            <form class="search" action="{% url 'user:search' %}" method="get">
                <input class='search' type="text" placeholder="SEARCH" name="query">
            </form>
        </div>
    </section></section>


    <div class="holder">

    </div>

    
    <section class="body">
        <div class="body-inner">
            <div class="cover"><img class="cover" src="{% static 'img/sakura.jpg' %}"></div>
            <img class="profile" src="{{ user.userinfo.picture.url }}">
            <div class="headname"><b2>{{ user.first_name }} {{ user.last_name }} </b2></div>
            <div class="breaker"></div>

            {% for book in rated %}
                <div class="book-info">
                    <img class="bookurl" src="{{ book.book.imageurl }}">
                    <div class="book-text">
                        <p5 class="booktitle">{{ book.book.title }}</p5>    
                    </div>
                    <div class="rate-star">
                        {% for i in "stars" %}
                            <span>
                            <form class="rate-star" action="{% url 'user:rate' %}" method="post" >
                                {% csrf_token %}
                                <input type="hidden" value="{{ forloop.counter0 }}" name="rating">
                                <input type="hidden" value="{{ book.book.id }}" name="bookid">
                                <button type="submit" class="rate-star">
                                    {% if book.rating > forloop.counter0 %}
                                        </c><i class="fa fa-star" aria-hidden="true"></i></c>
                                    {% else %}
                                        </c><i class="fa fa-star-o" aria-hidden="true"></i></c>
                                    {% endif %}
                                </span>
                                </button>
                            </form>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
    </section></section>

    </section></section>

</body>

</html>

user/templates/user/register.html
<!DOCTYPE html5>
<html>

<head>
    {% load static %}
    <title>Tindle - Register</title>
    <script src="https://use.fontawesome.com/68a025e94e.js"></script>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/png">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>


<body>
    <section class="wrap"><section class="wrapin"><section class="main"><div class="head">
        <div class="title"><h0>Register</h0> <img class="side-logo" src="{% static 'img/favicon.png' %}"></div><br>
        <div class="userinput">
            <form action="{% url 'user:create' %}" method="post">
                {% csrf_token %}
                <table class="basic">

                    <tr>
                        <th class="basic" align="right">
                            <p5>USERNAME</p5>
                        </th><th class="basic" align="left">
                            <input class="basic" type="text" name="username">
                        </th><th class="basic" align="right">
                            <p5>PASSWORD</p5>
                        </th><th class="basic" align="left">
                            <input class="basic" type="password" name="password">
                        </th>
                    </tr><tr>
                        <th colspan="2"></th>
                        <th class="basic" align="right">
                            <p5>CONFIRM<br>PASSWORD</p5>
                        </th><th class="basic" align="left">
                            <input class="basic" type="password" name="confirm">
                        </th>
                    </tr><tr>
                        <th colspan="4"><h1></h1></th>
                    </tr><tr>
                        <th class="basic" align="right">
                            <p5>FIRST<br>NAME</p5>
                        </th><th class="basic" align="left">
                            <input class="basic" type="text" name="name_first">
                        </th><th class="basic" align="right">
                            <p5>LAST<br>NAME</p5>
                        </th><th class="basic" align="left">
                            <input class="basic" type="text" name="name_last">
                        </th>
                    </tr><tr>
                        <th class="basic" align="right">
                            <p5>BIRTH<br>DATE</p5>
                        </th><th class="basic" align="left">
                            <input class="basic" type="date" value="2003-02-27" name="birthdate">
                        </th><th class="basic" align="right">
                            <p5>EMAIL</p5>
                        </th><th class="basic" align="left">
                            <input class="basic" type="text" name="email">
                        </th>
                    </tr><tr>
                        <th class="basic" align="right">
                            <p5>INTERESTED<br>IN</p5>
                        </th><th class="basic" align="left">
                            <select name="interest">
                                <option value="books">Books</option>
                                <option value="male">Male</option>
                                <option value="female">Female</option>
                            </select>
                        </th><th class="basic" align="right">
                            <p5>GENDER</p5>
                        </th><th class="basic" align="left">
                            <select name="gender">
                                <option value="male">Male</option>
                                <option value="female">Female</option>
                            </select>
                        </th>
                        
                    </tr><tr>
                        <th class="basic" colspan="4" align="center">
                            <input class="basic" type="submit" value="REGISTER">
                            <a href="{% url 'user:login'%}">
                                <input class="login" type="button" value="LOG IN">
                            </a>
                        </th>
                    </tr>
                </table>
            </form>
        </div>
    </div></section></section></section>

</body>

</html>

user/templates/user/search.html
<!DOCTYPE html5>
<html>

<head>
    {% load static %}
    <title>{{ user.username }}</title>
    <script src="https://use.fontawesome.com/68a025e94e.js"></script>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/png">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>


<body>

    <section class="navbar"><section class="navbar-inner">
        <div class="nav-item left">
            <b3>Tindle</b3><img class="nav-logo" src="{% static 'img/favicon.png' %}">
        </div><a href="{% url 'user:logout' %}"><div class="nav-item right gray">
            <p><i class="fa fa-power-off fa-lg down transparent" aria-hidden="true"></i></p>
        </div></a><div class="nav-item right gray">
            <p><i class="fa fa-tachometer fa-lg down transparent" aria-hidden="true"></i></p>
        </div><a href="{% url 'user:profile' %}"><div class="nav-item right gray">
            <p><p6>{{ user.first_name|upper }} {{ user.last_name|upper }}</p6></p>
        </div></a><div class="nav-item right">
            <img class="nav-thumb" src="{{ user.userinfo.picture.url }}">
        </div>


        
        <div class="search">
            <form class="search" action="{% url 'user:search' %}" method="get">
                <input class='search' type="text" placeholder="SEARCH" name="query">
            </form>
        </div>
    </section></section>


    <div class="holder">

    </div>

    
    <section class="body">
        <div class="body-inner">
            {% for book in isbn %}
                <div class="book-info">
                    <img class="bookurl" src="{{ book.imageurl }}">
                    <div class="book-text">
                        <p5 class="booktitle">{{book.title}}</p5>    
                    </div>
                    <div class="rate-star">
                        {% for i in "stars" %}
                            <span>
                            <form class="rate-star" action="{% url 'user:rate' %}" method="post" >
                                {% csrf_token %}
                                <input type="hidden" value="{{ forloop.counter0 }}" name="rating">
                                <input type="hidden" value="{{ book.id }}" name="bookid">
                                <button type="submit" class="rate-star">
                                    {% if book.rating > forloop.counter0 %}
                                        </c><i class="fa fa-star" aria-hidden="true"></i></c>
                                    {% else %}
                                        </c><i class="fa fa-star-o" aria-hidden="true"></i></c>
                                    {% endif %}
                                </span>
                                </button>
                            </form>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            {% for book in author %}
                <div class="book-info">
                    <img class="bookurl" src="{{ book.imageurl }}">
                    <div class="book-text">
                        <p5 class="booktitle">{{book.title}}</p5>    
                    </div>
                    <div class="rate-star">
                        {% for i in "stars" %}
                            <span>
                            <form class="rate-star" action="{% url 'user:rate' %}" method="post" >
                                {% csrf_token %}
                                <input type="hidden" value="{{ forloop.counter0 }}" name="rating">
                                <input type="hidden" value="{{ book.id }}" name="bookid">
                                <button type="submit" class="rate-star">
                                    {% if book.rating > forloop.counter0 %}
                                        </c><i class="fa fa-star" aria-hidden="true"></i></c>
                                    {% else %}
                                        </c><i class="fa fa-star-o" aria-hidden="true"></i></c>
                                    {% endif %}
                                </span>
                                </button>
                            </form>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            {% for book in title %}
                <div class="book-info">
                    <img class="bookurl" src="{{ book.imageurl }}">
                    <div class="book-text">
                        <p5 class="booktitle">{{ book.title }}</p5>    
                    </div>
                    <div class="rate-star">
                        {% for i in "stars" %}
                            <span>
                            <form class="rate-star" action="{% url 'user:rate' %}" method="post" >
                                {% csrf_token %}
                                <input type="hidden" value="{{ forloop.counter0 }}" name="rating">
                                <input type="hidden" value="{{ book.id }}" name="bookid">
                                <button type="submit" class="rate-star">
                                    {% if book.rating > forloop.counter0 %}
                                        </c><i class="fa fa-star" aria-hidden="true"></i></c>
                                    {% else %}
                                        </c><i class="fa fa-star-o" aria-hidden="true"></i></c>
                                    {% endif %}
                                </span>
                                </button>
                            </form>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
    </section></section>

</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

<!--script>
    $(document).ready(function () {
        $('form.rate-star').on('submit', function(e) {
            e.preventDefault();
            $.ajax({
                url : $(this).attr('action') || window.location.pathname,
                type: "POST",
                data: $(this).serialize(),
                success: function (data) { $("form_output").html(data); },
                error: function (jXHR, textStatus, errorThrown) { alert(errorThrown); }
            });
        });
    });
</script-->
</html>